= Tuples and pairs - Write the FindMaxRepetitionCount function.
:toc:
:toc-placement!:

toc::[]

# Introduction

This is a third task from coursera.org course yellow belt on C plusplus:
https://www.coursera.org/learn/c-plus-plus-yellow/programming/pg1Vd/massa-blokov

The files in this project are below:

```
.
├── src
│   ├── main.cc
│   ├── utils.cc
│   ├── utils.h
│   └── utils_unittest.cc
├── CMakeLists.txt
└── README.adoc
```

  * link:src/main.cc[src/main.cc] - Implements a command line interface
  * link:src/utils.cc[src/utils.cc] - Realization of utils module
  * link:src/utils.h[src/utils.h] - Interface for utils module
  * link:src/utils_unittest.cc[src/utils_unittest.cc] - Unit-tests for utils module using GTest

# Task description

There is a region database represented by the Region vector vector:

[source,c++]
----
struct Region {
  string std_name;
  string parent_std_name;
  map<Lang, string> names;
  int64_t population;
};
----

Here Lang is the language identifier:

[source,c++]
----
enum class Lang {
  DE, FR, IT
};
----

Write the FindMaxRepetitionCount function that takes a region database and determines which maximum number of retries it contains. Two records (objects of type Region) are considered different if they differ by at least one field.

[source,c++]
----
int FindMaxRepetitionCount (const vector <Region> & regions);
----

If all records are unique, count the maximum number of repeats to 1. If there are no records, return 0. It is guaranteed that the type int is sufficient to store the response.

# Input format

[source,c++]
----
int main() {
  cout << FindMaxRepetitionCount({
      {
          "Moscow",
          "Russia",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou"}, {Lang::IT, "Mosca"}},
          89
      }, {
          "Russia",
          "Eurasia",
          {{Lang::DE, "Russland"}, {Lang::FR, "Russie"}, {Lang::IT, "Russia"}},
          89
      }, {
          "Moscow",
          "Russia",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou"}, {Lang::IT, "Mosca"}},
          89
      }, {
          "Moscow",
          "Russia",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou"}, {Lang::IT, "Mosca"}},
          89
      }, {
          "Russia",
          "Eurasia",
          {{Lang::DE, "Russland"}, {Lang::FR, "Russie"}, {Lang::IT, "Russia"}},
          89
      },
  }) << endl;

  cout << FindMaxRepetitionCount({
      {
          "Moscow",
          "Russia",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou"}, {Lang::IT, "Mosca"}},
          89
      }, {
          "Russia",
          "Eurasia",
          {{Lang::DE, "Russland"}, {Lang::FR, "Russie"}, {Lang::IT, "Russia"}},
          89
      }, {
          "Moscow",
          "Russia",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou deux"}, {Lang::IT, "Mosca"}},
          89
      }, {
          "Moscow",
          "Toulouse",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou"}, {Lang::IT, "Mosca"}},
          89
      }, {
          "Moscow",
          "Russia",
          {{Lang::DE, "Moskau"}, {Lang::FR, "Moscou"}, {Lang::IT, "Mosca"}},
          31
      },
  }) << endl;

  return 0;
}
----

# Output format

[source,c++]
----
output
3
1
----
